FROM php:8.0-fpm

RUN apt-get update \
    && apt-get install -y \
        bash \
        libpq-dev \
        libicu-dev \
        libzip-dev \
        zip

        RUN docker-php-ext-configure zip \
    && docker-php-ext-install \
        pdo \
        pdo_pgsql \
        intl \
        zip

RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl --insecure https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer \
    && composer self-update

ADD php.ini /usr/local/etc/php/conf.d/

WORKDIR /var/www
COPY ./docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
